/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'tts': EventHandler<unknown, { topic: 'tts.completed'; data: unknown }>
    'sketch-storyboard-api': ApiRouteHandler<unknown, unknown, never>
    'script-gen': EventHandler<unknown, { topic: 'scripts.generated'; data: unknown }>
    'scrape-site': EventHandler<unknown, { topic: 'site.scraped'; data: unknown }>
    'render-status-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'render-api': ApiRouteHandler<unknown, unknown, never>
    'project-status-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'image-gen': EventHandler<unknown, { topic: 'images.generated'; data: unknown }>
    'health-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'generate-ad-api': ApiRouteHandler<unknown, unknown, { topic: 'ad.generation.started'; data: unknown }>
    'enqueue-renders': EventHandler<unknown, never>
    'download-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'content-moderation': EventHandler<unknown, { topic: 'moderation.passed'; data: unknown }>
    'cleanup-old-projects': CronHandler<never>
    'brand-extract': EventHandler<unknown, { topic: 'brand.extracted'; data: unknown }>
    'analytics-agent': EventHandler<unknown, { topic: 'analytics.scored'; data: unknown }>
  }
    
}